<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>SB Admin 2 - Bootstrap Admin Theme</title>
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
        <link href="/css/plugins/timeline.css" rel="stylesheet">
        <link href="/css/sb-admin-2.css" rel="stylesheet">
        <link href="/css/plugins/morris.css" rel="stylesheet">
        <link href="/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->menu->getMenu(); ?>
            <?php echo $this->getContent(); ?>
        </div>
        <script src="/js/jquery.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/plugins/metisMenu/metisMenu.min.js"></script>
        <script src="/js/plugins/morris/raphael.min.js"></script>
        <script src="/js/plugins/morris/morris.min.js"></script>
        <script src="/js/plugins/morris/morris-data.js"></script>
        <script src="/js/sb-admin-2.js"></script>
    </body>
</html>